Repository krahyor/backend_camphub, pull requests merged in 2025-09, with the labels that each got.

#43 feat, refactor
  README.md
  app/db/init_data.py
  app/models/__init__.py
  app/models/course_model.py
  app/models/course_schedule_model.py
  app/models/enrollment_model.py
  app/routers/__init__.py
  app/routers/endpoints/course_schedule_route.py
  app/schemas/course_schedule_schema.py
Labels: feature, Backend, Not Review

#49 feat: Add demo announcements initialization and update routes to enfo…
  app/db/init_data.py
  app/routers/endpoints/announcement_route.py
  app/routers/endpoints/course_schedule_route.py
Labels: reviewed, Backend

#50 เพิ่มเติมการคำนวณอายุจากวันเกิด สร้าง Function fullname ส่งไปยัง API
  README.md
  app/models/user_model.py
  app/routers/endpoints/announcement_route.py
  app/routers/endpoints/auth_route.py
  app/routers/endpoints/course_schedule_route.py
  app/routers/endpoints/user_route.py
  app/schemas/user_schema.py
Labels: reviewed, feature, Backend

#75 เพิ่มระบบรองรับการแชร์ลิงค์
  app/db/init_data.py
  app/routers/endpoints/event_route.py
Labels: feature, Backend

#81 สร้าง API สำหรับจัดการ Room และ Location และปรับปรุง Service CourseSchedule
  app/routers/__init__.py
  app/routers/endpoints/location_route.py
  app/routers/endpoints/room_route.py
  app/services/course_schedule_service.py
  app/services/location_service.py
  app/services/room_service.py
Labels: feature, Backend

#82 เพิ่มให้หน้าบ้านเรียกใช้ API แสดงวิชาที่ User คนนั้น ๆ ลงทะเบียนไว้ได้
  app/routers/endpoints/enrollment_route.py
  app/schemas/enrollment_schema.py
  app/services/enrollment_service.py
Labels: enhancement, Backend

#83 เพิ่ม mock_data ใน database ของ Room Location และ EnrollmentCourse
  app/db/init_data.py
  app/schemas/user_schema.py
  scripts/init_data.py
Labels: Backend, chores

#101 เพิ่ม Test และ Coverage ในJenkins Pipeline และ แสดงผลที่ SonarQube
  Jenkinsfile
  app/routers/endpoints/announcement_route.py
  app/routers/endpoints/event_route.py
  app/schemas/user_schema.py
  app/services/course_schedule_service.py
  app/services/courses_service.py
  app/services/event_enrollment_service.py
  app/services/location_service.py
  app/services/room_service.py
  dockerfile
  tests/test_announcement.py
Labels: enhancement, Backend, Not Review

#115 feat: add locust load testing script
  app/routers/endpoints/announcement_route.py
  app/routers/endpoints/bookmark_route.py
  app/routers/endpoints/courses_route.py
  app/routers/endpoints/room_route.py
  app/schemas/event_schema.py
  locustfile.py
  pyproject.toml
  tests/test_announcement.py
Labels: enhancement, Backend
